Transform: "AWS::Serverless-2016-10-31"

Resources:
  ConfigRule:
    Type: AWS::Config::ConfigRule
    DependsOn: LambdaPermission
    Properties:
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: !GetAtt Function.Arn
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification
      InputParameters:
        debug: false

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ec2_security_group_ingress.lambda_handler
      Runtime: python2.7
      Timeout: 30
      Policies:
      - Statement:
        - Effect: Allow
          Action:
            - config:PutEvaluations
            - ec2:DescribeSecurityGroups
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:RevokeSecurityGroupIngress
          Resource: "*"
      CodeUri: ec2_security_group_ingress.py

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Function.Arn
      Principal: config.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
